#!/usr/bin/env bash
##
## Example ~/.config/labwc/environment file.
## Uncomment lines starting with one '#' to suit your needs.
##

##
## Set cursor theme and size. Find system icons themes with:
## `find /usr/share/icons/ -type d -name "cursors"`
##

XCURSOR_THEME=posys_cursor_scalable_black
#XCURSOR_THEME=capitaine-cursors
XCURSOR_SIZE=32


##
## This allows xdg-desktop-portal-wlr to function (e.g. for screen-recording).
## It is automatically set to "labwc:wlroots" by labwc though, so it is only
## included here for completeness. Again, labwc will not over-write an
## already set environment variable, so if you need it set to something else,
## then uncomment and adjust.
##

XDG_CURRENT_DESKTOP=labwc:wlroots
