# My own wallpaper I made
$wallpaper1 = $HOME/dotfiles/themes/wallpapers/bees_on_yellow.jpg

wallpaper {
    monitor = DP-2
    path = $wallpaper1
    fit-mode = cover
}

wallpaper {
    monitor = DP-1
    path = $wallpaper1
    fit-mode = cover
}

splash = true

